name: cardinal
description: The declarative and elegant CLI framework for Dart.
version: 0.1.1
repository: https://github.com/alomia/cardinal
homepage: https://github.com/alomia/cardinal
issue_tracker: https://github.com/alomia/cardinal/issues

environment:
  sdk: ^3.10.1

topics:
  - cli
  - framework
  - tools
  - developer

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  yaml: ^3.1.3
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
